### ISSUE TITLE
Publish the module as a community module in the Testcontainers modules catalog

### ISSUE THREAD

**Issue by mdelapenya** [abhirockzz/dynamodb-local-testcontainers-go#1]
HI 👋 from Testcontainers for Go! I'd like to thank you for creating this module, looks fantastic and following the best practices we recommend in our modules.

I read [this post](https://www.linkedin.com/posts/dynamo14324_summary-learn-how-to-run-and-test-dynamodb-activity-7160956552646926336-cDrs?utm_source=share&utm_medium=member_desktop) on LinkedIn and its related [blog post](https://dev.to/aws/run-and-test-dynamodb-applications-locally-using-docker-and-testcontainers-108i), and I'd like to personally thank you for creating a new module 🙇 

Would you be interested in publishing this module as part of the community catalog here? https://github.com/testcontainers/community-module-registry Just follow the instructions in there, it's super easy.

**Comment by abhirockzz** [comment]
@mdelapenya Thanks for the kind words. 

Added the module - https://github.com/testcontainers/community-module-registry/pull/22
